name = "PumpProbeModels"
uuid = "c045c9a4-9cbd-11e9-012e-3d86e60c81ee"
authors = ["MLackner <lacknersmichael@gmail.com>"]
version = "0.1.0"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[targets]
test = ["BenchmarkTools"]
